export const projects = [
  {
    title: 'World Country App',
    description: "Small application for searching data about a country by its partial or full name. Use the Rest Countries API.",
      image: '/images/1.png',
      tags: ['JavaScript', 'HTML/CSS', 'Handlebars', 'Webpack'],
    // source: 'https://b-vitalii.github.io/js-hw-12-Counties-App',
    visit: 'https://github.com/b-vitalii/js-hw-12-Counties-app',
    id: 0,
  },
  {
    title: 'Phonebook App',
    description:"Phonebook contacts storage application.",
    image: '/images/2.png',
    tags: ['React JS', 'HTML/CSS'],
    // source: 'http://b-vitalii.github.io/react-hw-03-phonebook',
    visit: 'https://github.com/b-vitalii/react-hw-03-Phonebook/tree/master',
    id: 1,
  },
  {
    title: 'Chat App',
    description: "Сhat application for SKYUP team. With good design, image support and online statuses.",
      image: '/images/3.png',
      tags: ['React JS', 'ChatEngine', 'HTML/CSS'],
    // source: 'http://gitname.github.io/react-chat_app',
    visit: 'https://github.com/b-vitalii/react-chat_app/tree/master',
    id: 2,
  },
  {
    title: 'Weather App',
    description: "Small but very beautiful and functional PWA weather application.",
    image: '/images/4.png',
    tags: ['React JS', 'HTML/CSS'],
    // source: 'http://b-vitalii.github.io/weather-app-pwa',
    visit: 'https://github.com/b-vitalii/weather-app-pwa/tree/master',
    id: 3,
  },
  {
    title: 'Menu Page',
    description: "Menu page with the ability to choose a theme for the food ordering service.",
    image: '/images/5.png',
    tags: ['JavaScript', 'HTML/CSS', 'Handlebars'],
    // source: 'https://b-vitalii.github.io/js-hw-10',
    visit: 'https://github.com/b-vitalii/js-hw-10',
    id: 4,
  },
  {
    title: 'Feedback App',
    description: "Most businesses, collects testimonials from its customers. I have created an application for collecting statistics. There are only three types of feedback: good, neutral, and bad.",
    image: '/images/6.png',
    tags: ['React JS', 'HTML/CSS'],
    // source: 'https://b-vitalii.github.io/react-hw-02-feedback',
    visit: 'https://github.com/b-vitalii/react-hw-02-feedback/tree/master',
    id: 5,
  },
  {
    title: 'Gallery',
    description: "A simple gallery with the ability to click on its elements and view the full-size image in a modal window.",
    image: '/images/7.png',
    tags: ['JavaScript', 'HTML/CSS'],
    // source: '#projects',
    visit: 'https://github.com/b-vitalii/js-hw-08',
    id: 6,
  },
  {
    title: 'Pixabay Gallery',
    description: "Small application to search and view images by keyword. The public Pixabay API is used for HTTP requests, the application also supports pagination.",
    image: '/images/8.png',
    tags: ['JavaScript', 'Handlebars', 'HTML/CSS', 'Webpack'],
    // source: 'https://b-vitalii.github.io/js-hw-13-Pixabay-gallery/',
    visit: 'https://github.com/b-vitalii/js-hw-13-Pixabay-gallery',
    id: 7,
  },
  {
    title: 'Social Network Page',
    description: "Social network profile, with statistics, friends list and transaction history.",
    image: '/images/9.png',
    tags: ['React JS', 'HTML/CSS'],
    // source: 'https://b-vitalii.github.io/react-hw-01',
    visit: 'https://github.com/b-vitalii/react-hw-01',
    id: 8,
  },
  {
    title: 'Aviation-Quiz',
    description: "An aviation-themed game that will appeal not only to aviation geeks, but also people who want to test their knowledge in this area.",
    image: '/images/12.png',
    tags: ['React JS', 'HTML/CSS'],
    // source: '',
    visit: 'https://github.com/b-vitalii/aviation-quiz/tree/master',
    id: 9,
  },
  {
    title: 'Telegram-BOT',
    description: "Telegram bot, which includes a little useful functionality.",
    image: '/images/11.png',
    tags: ['NODE JS'],
    // source: '',
    visit: 'https://github.com/b-vitalii/telegram_bot',
    id: 10,
  },
  {
    title: 'Psychologist website',
    description: "Psychologist's website, which will provide general information about counseling techniques, as well as the ability to conduct online consultations.",
    image: '/images/10.png',
    tags: ['React', 'Next JS'],
    // source: '#projects',
    visit: '#projects',
    id: 11,
  }
];

export const foto = [{
    title: 'Foto',
    description: "My foto",
    image: '/images/foto.png',
    id: 10,
  }];

